name: changes_info
on: [pull_request]

jobs:
  changes_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt-get install libyaml-dev
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            file_count=$(find pokesets/ -name "$changed_file" | wc -l)
            if [[ $changed_file == pokesets/* && ( $changed_file == *.yaml || $changed_file == *.yml ) ]]; then
              echo "$changed_file is a pokeset"
              python -m pokecat populate "${changed_file}" _tmp_populated.yaml
              python -m pokecat instantiate _tmp_populated.yaml _tmp_instantiated.json
              comment=$(cat _tmp_instantiated.json | jq --raw-output '.[] | "\(.setname): \(.stats)"')
              echo "test comment: ${comment}."
            else
              echo "$changed_file is not a pokeset"
            fi
          done
